apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: <your namespace>
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: mynode
        image: <node image name>
