kind: Service
apiVersion: v1
metadata:
  name: nodeapp-service
  namespace: jkidd
spec:
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 80   
    targetPort: 3000
  type: LoadBalancer
